#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

DAEMON=/usr/sbin/x2gocleansessions

depend() {
	need postgresql
	use sshd
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --pidfile /var/run/${SVCNAME}.pid \
		--exec ${DAEMON} -- $DAEMON_OPTS

	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile /var/run/${SVCNAME}.pid
	eend $?
}
